//
//  IOObservableScrollViewPreviewData.swift
//  
//
//  Created by Adnan ilker Ozcan on 20.05.2023.
//

import Foundation

#if DEBUG
struct IOObservableScrollViewPreviewData {
    
    // MARK: - Data
    
    static var previewData = [
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "Ut in leo id sem iaculis porta.",
        "Aenean sodales leo ac nunc congue, vitae eleifend nibh dapibus.",
        "Integer mattis elit sed ipsum molestie, vel maximus orci rhoncus.",
        "Nulla ultrices ligula a vulputate pellentesque.",
        "Morbi quis ante non lorem facilisis sollicitudin.",
        "Nam dictum tellus aliquet augue venenatis, faucibus posuere dolor bibendum.",
        "Curabitur at massa ullamcorper, dapibus urna eu, tempor nisi.",
        "Pellentesque eu elit ac augue venenatis varius sit amet vel purus.",
        "Ut sit amet odio vel leo finibus posuere.",
        "Ut in sem suscipit, convallis felis ac, dapibus quam.",
        "Etiam ac sem ac odio condimentum commodo.",
        "Integer egestas nisl eget ipsum tincidunt pharetra.",
        "Integer ut libero aliquam, luctus nunc et, maximus tellus.",
        "Fusce consequat lectus quis augue posuere, et porta ipsum hendrerit.",
        "Etiam in libero eu erat dignissim auctor.",
        "Sed eu ante blandit, aliquet mauris a, pharetra est.",
        "Vivamus quis nunc ut dui lacinia facilisis.",
        "Quisque condimentum nisi at laoreet sagittis.",
        "Cras ultricies diam in enim egestas vestibulum.",
        "In varius mauris non risus fermentum maximus.",
        "Proin nec diam quis enim hendrerit gravida.",
        "Quisque ullamcorper sapien condimentum maximus efficitur.",
        "Nunc congue augue vitae lorem posuere pretium.",
        "Vivamus ornare augue ac varius bibendum.",
        "Proin malesuada orci condimentum massa finibus auctor.",
        "Donec at urna eget ligula semper pharetra.",
        "Praesent vel neque at metus maximus vulputate.",
        "Fusce at ligula a eros pulvinar auctor.",
        "Nullam et nibh in orci laoreet porta.",
        "Nullam aliquam orci ut augue tempor, nec scelerisque leo pulvinar.",
        "Curabitur condimentum lorem sed ultrices tincidunt.",
        "Phasellus ornare dolor sed neque placerat accumsan.",
        "Fusce nec dui rutrum, fringilla dui ac, vestibulum risus.",
        "Morbi condimentum lacus rutrum mauris viverra blandit.",
        "Pellentesque malesuada felis sed mauris condimentum euismod nec sit amet justo.",
        "Maecenas non elit sagittis neque laoreet iaculis in quis nulla.",
        "Praesent ultricies mauris accumsan quam venenatis elementum.",
        "Cras convallis urna sit amet congue efficitur.",
        "Aliquam sodales magna ac metus malesuada feugiat.",
        "Vivamus in lectus congue, tincidunt magna vitae, ultrices diam.",
        "Nunc vel purus maximus, dignissim metus ac, blandit felis.",
        "Aenean tempus ligula vitae velit consectetur posuere.",
        "Nulla nec justo at sapien ultrices rhoncus.",
        "Sed a nunc a neque mattis pharetra.",
        "Sed fermentum erat sit amet risus molestie, tristique facilisis ipsum interdum.",
        "Etiam sit amet risus non urna venenatis facilisis.",
        "In nec arcu ac mi tristique interdum.",
        "Aliquam dapibus enim in faucibus elementum.",
        "Integer dapibus risus et sapien semper, sed lacinia massa volutpat.",
        "Morbi varius lacus ultricies augue lobortis suscipit.",
        "Fusce eget odio et ante congue ultrices.",
        "Nulla nec arcu accumsan, pretium dui volutpat, maximus neque.",
        "Nunc et purus vel risus iaculis luctus.",
        "Sed molestie neque nec enim feugiat, in finibus diam accumsan.",
        "Aliquam nec metus a diam volutpat iaculis.",
        "Curabitur in quam et massa suscipit euismod id quis neque.",
        "Sed posuere nunc ac fermentum malesuada.",
        "Donec a magna elementum lacus aliquet vehicula.",
        "Cras luctus sapien sed gravida commodo.",
        "Nunc porta dolor id magna ornare luctus.",
        "Aliquam sit amet felis ultricies nisl mattis semper.",
        "Cras et leo in ligula hendrerit dapibus.",
        "Curabitur ut neque semper, pretium mauris et, gravida leo.",
        "Nullam accumsan neque vel lacus ultrices, ac porttitor velit fringilla.",
        "Morbi quis sem a ipsum luctus convallis eu ut nunc.",
        "Donec ullamcorper ipsum a dapibus ultrices.",
        "Sed egestas dolor sed accumsan pretium.",
        "Vestibulum vitae arcu quis tellus viverra blandit.",
        "Vestibulum nec risus nec nibh pharetra elementum.",
        "Fusce at velit pharetra, aliquam orci non, elementum ligula.",
        "Integer quis arcu euismod dui hendrerit feugiat sit amet quis augue.",
        "Nulla eu nunc non velit egestas dignissim vitae in diam.",
        "Etiam pretium lorem a mi imperdiet, nec elementum neque gravida.",
        "Nullam luctus urna ac justo gravida, in lacinia velit accumsan.",
        "Quisque feugiat dolor eget magna posuere interdum.",
        "Donec quis nisi ultricies, malesuada mi sollicitudin, venenatis lectus.",
        "Aenean blandit justo at quam ullamcorper convallis.",
        "Mauris vitae nibh quis quam aliquet viverra nec sed ante.",
        "Morbi nec sem eget tortor elementum auctor.",
        "Etiam vestibulum justo at ligula fringilla tempus.",
        "Suspendisse congue sem et mauris molestie ultrices.",
        "Phasellus faucibus ex nec porta scelerisque.",
        "Nam commodo lacus vitae odio consectetur tempor.",
        "Suspendisse egestas mauris et felis ornare convallis quis ac odio.",
        "Maecenas vel enim eget leo dignissim efficitur.",
        "Vestibulum aliquam orci quis metus blandit placerat.",
        "Nullam ut ipsum pulvinar, mattis massa id, imperdiet libero.",
        "In rutrum ipsum vitae sapien commodo cursus.",
        "Curabitur malesuada sapien sit amet augue tincidunt, sed lacinia nulla vestibulum.",
        "Cras in dolor id justo facilisis fringilla.",
        "Etiam dapibus nibh id lectus sagittis, id maximus mauris mattis.",
        "Donec auctor orci vitae commodo tempor.",
        "Nunc porttitor lorem sit amet rhoncus viverra.",
        "Aenean ornare ante at sapien imperdiet, nec dapibus ligula pretium.",
        "Morbi auctor eros at elit pharetra eleifend.",
        "Suspendisse rutrum justo ut interdum elementum.",
        "Pellentesque sit amet mi ultricies, gravida enim quis, pharetra est.",
        "Ut suscipit quam in orci tempus interdum.",
        "Sed vitae nisl in turpis placerat porta.",
        "Sed fringilla nisl quis orci eleifend, a mollis sapien auctor.",
        "Morbi non dui fringilla, sagittis lectus sit amet, dapibus eros.",
        "Sed a elit egestas lacus commodo placerat in non ex.",
        "Vivamus id orci et justo dapibus sollicitudin sit amet eget lacus.",
        "Proin gravida nibh non massa tincidunt, porttitor pulvinar leo sodales.",
        "Nullam et nulla quis massa pellentesque tincidunt.",
        "Fusce lacinia ex egestas, porta nulla egestas, convallis libero.",
        "Vivamus rutrum orci non dolor blandit efficitur.",
        "Mauris a enim vitae lorem facilisis scelerisque in a nulla.",
        "Pellentesque vel dolor ut erat posuere aliquet interdum ac tortor.",
        "Praesent id enim rutrum, mollis enim eget, accumsan magna.",
        "Morbi tincidunt urna sit amet erat iaculis mollis.",
        "Curabitur imperdiet magna eget consequat semper.",
        "Fusce in arcu scelerisque lorem posuere lacinia.",
        "Nullam varius sapien in nunc tincidunt, in pharetra nunc porttitor.",
        "Fusce sed lacus dignissim, blandit orci at, molestie odio.",
        "Nunc suscipit massa dignissim massa tempus, a lacinia lacus porttitor.",
        "Curabitur id ipsum et dui tincidunt varius.",
        "In tempor neque vel nisl sagittis euismod.",
        "Nunc tincidunt risus vitae fermentum feugiat.",
        "Nullam blandit erat nec mauris lobortis, et ultrices nibh fringilla."
    ]
}
#endif
