excluded:
    - Carthage
    - Pods
    - Libraries

comma: error

line_length:
    warning: 6000
    error: 6000

file_length:
    warning: 1000
    error: 1000

function_body_length:
    warning: 160
    error: 160

type_body_length:
    warning: 900
    error: 900

cyclomatic_complexity: 
    warning: 25
    error: 25

vertical_whitespace:
    max_empty_lines: 1
    severity: error

comment_spacing:
    severity: error

void_function_in_ternary:
    severity: error

colon:
    severity: error
    flexible_right_spacing: false
    apply_to_dictionaries: true

trailing_comma:
    severity: error
    mandatory_comma: false

statement_position:
    severity: error
    statement_mode: default

opening_brace:
    severity: error
    allowMultilineFunc: false

return_arrow_whitespace:
    severity: error

control_statement:
    severity: error

empty_parentheses_with_trailing_closure:
    severity: error

for_where:
    severity: error

multiple_closures_with_trailing_closure:
    severity: error

unused_closure_parameter:
    severity: error

trailing_semicolon:
    severity: error

trailing_newline:
    severity: error
    mandatory_comma: false

unused_optional_binding:
    severity: error
    ignore_optional_try: false

redundant_optional_initialization:
    severity: error

private_over_fileprivate:
    severity: error
    validate_extensions: false

redundant_string_enum_value:
    severity: error

unneeded_break_in_switch:
    severity: error

redundant_type_annotation:
    severity: error

operator_usage_whitespace:
    severity: error

explicit_init:
    severity: error

private_action:
    severity: error

overridden_super_call:
    severity: error

prefer_zero_over_explicit_init:
    severity: error

indentation_width:
    severity: error
    indentation_width: 4
    include_comments: false

multiline_arguments_brackets:
    severity: error

private_outlet:
    severity: error

vertical_whitespace_between_cases:
    severity: error

weak_delegate:
    severity: error

unneeded_parentheses_in_closure_argument:
    severity: error

toggle_bool:
    severity: error

yoda_condition:
    severity: error

prefixed_toplevel_constant:
    severity: error

switch_case_alignment:
    severity: error

switch_case_on_newline:
    severity: error

closure_end_indentation:
    severity: error

mark:
    severity: error

void_return:
    severity: error

literal_expression_end_indentation:
    severity: error

computed_accessors_order:
    severity: error
    order: get_set

multiline_literal_brackets:
    severity: error

closure_parameter_position:
    severity: error

return_value_from_void_function:
    severity: error

redundant_nil_coalescing:
    severity: error

force_cast:
    severity: error

force_try:
    severity: error

extension_access_modifier:
    severity: error

function_parameter_count:
    warning: 10
    error: 10
    ignores_default_parameters: true

large_tuple:
    warning: 3
    error: 3

legacy_constructor:
    severity: error

notification_center_detachment:
    severity: error

multiline_parameters_brackets:
    severity: error

leading_whitespace:
    severity: error

syntactic_sugar:
    severity: error

self_in_property_initialization:
    severity: error

implicit_getter:
    severity: error

explicit_self:
    severity: error

unused_import:
    severity: error

capture_variable:
    severity: error

array_init:
    severity: error

class_delegate_protocol:
    severity: error

closure_spacing:
    severity: error

collection_alignment:
    severity: error

comma_inheritance:
    severity: error

compiler_protocol_init:
    severity: error

closing_brace:
    severity: error

contains_over_filter_count:
    severity: error

contains_over_filter_is_empty:
    severity: error

contains_over_first_not_nil:
    severity: error

contains_over_range_nil_comparison:
    severity: error

discarded_notification_center_observer:
    severity: error

discouraged_assert:
    severity: error

discouraged_direct_init:
    severity: error

discouraged_none_name:
    severity: error

duplicate_conditions:
    severity: error

duplicate_enum_cases:
    severity: error

duplicate_imports:
    severity: error

duplicated_key_in_dictionary_literal:
    severity: error

empty_parameters:
    severity: error

fallthrough:
    severity: error

file_name_no_space:
    severity: error

first_where:
    severity: error

function_default_parameter_at_end:
    severity: error

identical_operands:
    severity: error

implicit_return:
    severity: error

inert_defer:
    severity: error

is_disjoint:
    severity: error

joined_default_parameter:
    severity: error

last_where:
    severity: error

legacy_cggeometry_functions:
    severity: error

legacy_constant:
    severity: error

legacy_hashing:
    severity: error

legacy_multiple:
    severity: error

legacy_nsgeometry_functions:
    severity: error

legacy_random:
    severity: error

let_var_whitespace:
    severity: error

lower_acl_than_parent:
    severity: error

multiline_function_chains:
    severity: error

nimble_operator:
    severity: error

no_fallthrough_only:
    severity: error

ns_number_init_as_function_reference:
    severity: error

nsobject_prefer_isequal:
    severity: error

operator_whitespace:
    severity: error

override_in_extension:
    severity: error

period_spacing:
    severity: error

prefer_nimble:
    severity: error

prefer_self_type_over_type_of_self:
    severity: error

prefer_self_in_static_references:
    severity: error

private_subject:
    severity: error

protocol_property_accessors_order:
    severity: error

raw_value_for_camel_cased_codable_enum:
    severity: error

reduce_boolean:
    severity: error

reduce_into:
    severity: error

redundant_discardable_let:
    severity: error

redundant_objc_attribute:
    severity: error

redundant_set_access_control:
    severity: error

redundant_void_return:
    severity: error

self_binding:
    severity: error

shorthand_optional_binding:
    severity: error

sorted_imports:
    severity: error

static_operator:
    severity: error

strict_fileprivate:
    severity: error

unavailable_condition:
    severity: error

unowned_variable_capture:
    severity: error

unused_capture_list:
    severity: error

unused_control_flow_label:
    severity: error

unused_enumerated:
    severity: error

unused_setter_value:
    severity: error

vertical_parameter_alignment:
    severity: error

disabled_rules:
    - identifier_name
    - trailing_whitespace
    - type_name
    - inclusive_language
    - empty_enum_arguments
    - nesting

opt_in_rules:
    - empty_count
    - array_init
    - closure_end_indentation
    - collection_alignment
    - discarded_notification_center_observer
    - discouraged_object_literal
    - enum_case_associated_values_count
    - explicit_init
    - extension_access_modifier
    - fallthrough
    - ibinspectable_in_extension
    - identical_operands
    - indentation_width
    - last_where
    - literal_expression_end_indentation
    - multiline_arguments_brackets
    - multiline_literal_brackets
    - multiline_parameters_brackets
    - nimble_operator
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - prefer_nimble
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - prefixed_toplevel_constant
    - private_action
    - private_outlet
    - quick_discouraged_call
    - raw_value_for_camel_cased_codable_enum
    - reduce_into
    - redundant_nil_coalescing
    - redundant_type_annotation
    - return_value_from_void_function
    - static_operator
    - switch_case_on_newline
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - vertical_whitespace_between_cases
    - weak_delegate
    - xct_specific_matcher
    - yoda_condition
    - closure_spacing
    - comma_inheritance
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - discouraged_assert
    - file_name_no_space
    - first_where
    - function_default_parameter_at_end
    - implicit_return
    - inert_defer
    - joined_default_parameter
    - legacy_multiple
    - let_var_whitespace
    - lower_acl_than_parent
    - multiline_function_chains
    - period_spacing
    - prefer_self_in_static_references
    - private_subject
    - self_binding
    - shorthand_optional_binding
    - sorted_imports
    - strict_fileprivate
    - unowned_variable_capture
    - unused_capture_list
    - discouraged_none_name

analyzer_rules:
    - explicit_self
    - unused_import
    - unused_declaration
    - capture_variable

custom_rules:
    disable_print:
        included: ".*\\.swift"
        name: "print usage"
        regex: "((\\bprint)|(Swift\\.print))\\s*\\("
        message: "Use IOLogger.verbose instead of print"
        severity: error
    disable_debug_print:
        included: ".*\\.swift"
        name: "debug print usage"
        regex: "((\\bdebugPrint)|(Swift\\.debugPrint))\\s*\\("
        message: "Use IOLogger.verbose instead of debugPrint"
        severity: error
    disable_dump:
        included: ".*\\.swift"
        name: "dump print usage"
        regex: "((\\bdump)|(Swift\\.dump))\\s*\\("
        message: "Use IOLogger.verbose instead of dump"
        severity: error